### ISSUE TITLE
Expose the signature and certificate outputs in various ways

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/gh-action-sigstore-python#3]
We should think about how we want to expose these outputs, beyond placing them on the filesystem. Some ideas:

* Create [job outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) corresponding to each artifact.
    * Downsides: Job outputs aren't really intended for this, plus the naming with multiple inputs will be tricky.
* Create [workflow artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) corresponding to each artifact.
    * Downsides: None?
* Support attaching each artifact to the associated GitHub Release, if our action is run on a release workflow.
    * This should be configurable, not the default.

**Comment by tetsuo-cpp** [comment]
I think workflow artifacts are the right way to expose this information. They're a more natural fit for what we're after (as opposed to job outputs) and they can still be used in subsequent jobs.

I think that the idea about attaching artifacts for releases is good. I'll make a separate issue about that since I think that's enough work it should go in a separate PR.
